language: java

jdk:
  - oraclejdk8
sudo: false

script:
  - mvn clean
  - mvn evosuite:generate
  - mvn evosuite:export
  - mvn test
  - mvn evosuite:info
  - "mvn cobertura:cobertura"
after_success:
  - bash <(curl -s https://codecov.io/bash)

dist: trusty