/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 11 20:48:28 GMT 2022
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AVLTree_ESTest extends AVLTree_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      aVLTree0.delete(1);
      aVLTree0.delete(1);
      aVLTree0.insert(6621);
      aVLTree0.delete(0);
      AVLTree.Node aVLTree_Node0 = aVLTree0.new Node(0);
      aVLTree0.find((-4195));
      aVLTree_Node0.left = null;
      aVLTree_Node0.right = null;
      AVLTree.Node aVLTree_Node1 = aVLTree0.getRoot();
      aVLTree_Node0.right = aVLTree_Node1;
      aVLTree0.height();
      aVLTree_Node1.left = aVLTree_Node0.right;
      aVLTree0.getBalance(aVLTree_Node0);
      aVLTree0.getBalance(aVLTree_Node0);
      // Undeclared exception!
      aVLTree0.find(0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      int int0 = 1;
      aVLTree0.delete(1);
      aVLTree0.insert(1);
      aVLTree0.delete(0);
      aVLTree0.insert(0);
      AVLTree.Node aVLTree_Node0 = aVLTree0.find(0);
      aVLTree_Node0.height = 1;
      int int1 = 315;
      aVLTree_Node0.height = 315;
      // Undeclared exception!
      try { 
        aVLTree0.delete(111);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("AVLTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      int int0 = 834;
      aVLTree0.insert(834);
      int int1 = (-766);
      aVLTree0.insert((-766));
      aVLTree0.insert((-1394));
      aVLTree0.insert((-662));
      aVLTree0.delete((-766));
      aVLTree0.height();
      aVLTree0.height();
      int int2 = 0;
      aVLTree0.insert(0);
      aVLTree0.getRoot();
      aVLTree0.getRoot();
      aVLTree0.find(1);
      aVLTree0.find(1);
      aVLTree0.insert(1);
      int int3 = 2177;
      // Undeclared exception!
      try { 
        aVLTree0.insert(1);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // duplicate Key!
         //
         verifyException("AVLTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      aVLTree0.insert((-84));
      AVLTree.Node aVLTree_Node0 = aVLTree0.getRoot();
      aVLTree0.getBalance(aVLTree_Node0);
      AVLTree.Node aVLTree_Node1 = aVLTree0.getRoot();
      aVLTree_Node0.left = aVLTree_Node1;
      aVLTree_Node1.left = aVLTree_Node0;
      aVLTree_Node1.key = (-1708);
      aVLTree0.getBalance(aVLTree_Node1);
      aVLTree0.height();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      aVLTree0.insert(1364);
      aVLTree0.insert(0);
      aVLTree0.height();
      aVLTree0.insert(1);
      AVLTree.Node aVLTree_Node0 = aVLTree0.find(1);
      AVLTree.Node aVLTree_Node1 = aVLTree0.getRoot();
      aVLTree_Node0.right = aVLTree_Node1;
      aVLTree_Node0.key = 1503;
      aVLTree_Node0.height = 1;
      aVLTree0.getBalance(aVLTree_Node0);
      int int0 = 0;
      aVLTree0.delete(0);
      // Undeclared exception!
      try { 
        aVLTree0.delete(int0);
        fail("Expecting exception: StackOverflowError");
      
      } catch(StackOverflowError e) {
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      int int0 = 1;
      aVLTree0.delete(1);
      aVLTree0.insert(1);
      aVLTree0.delete(0);
      aVLTree0.insert(0);
      AVLTree.Node aVLTree_Node0 = aVLTree0.find(0);
      aVLTree_Node0.height = 1;
      int int1 = (-668);
      aVLTree_Node0.height = (-668);
      // Undeclared exception!
      try { 
        aVLTree0.delete(111);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("AVLTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      aVLTree0.delete(1);
      AVLTree.Node aVLTree_Node0 = aVLTree0.new Node(1);
      aVLTree0.insert(1);
      aVLTree0.insert((-2405));
      aVLTree0.delete(0);
      aVLTree0.insert(0);
      aVLTree0.height();
      aVLTree0.height();
      aVLTree0.height();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      aVLTree0.delete(0);
      aVLTree0.delete((-1));
      aVLTree0.delete((-1));
      aVLTree0.insert(0);
      int int0 = 1;
      aVLTree0.insert(1);
      int int1 = 0;
      AVLTree.Node aVLTree_Node0 = aVLTree0.new Node(0);
      aVLTree0.insert(437);
      aVLTree0.delete(1);
      aVLTree0.height();
      int int2 = 1;
      // Undeclared exception!
      try { 
        aVLTree0.insert(0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // duplicate Key!
         //
         verifyException("AVLTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      int int0 = 0;
      aVLTree0.insert(0);
      aVLTree0.insert((-1));
      // Undeclared exception!
      try { 
        aVLTree0.delete(0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("AVLTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      aVLTree0.insert(1);
      aVLTree0.delete((-818));
      aVLTree0.delete(0);
      aVLTree0.height();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      aVLTree0.insert((-770));
      aVLTree0.insert(2814);
      aVLTree0.height();
      AVLTree.Node aVLTree_Node0 = aVLTree0.getRoot();
      aVLTree0.getBalance(aVLTree_Node0);
      aVLTree0.getRoot();
      aVLTree0.delete((-770));
      aVLTree0.delete(2814);
      aVLTree0.find(0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      aVLTree0.getRoot();
      aVLTree0.getBalance((AVLTree.Node) null);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      aVLTree0.insert((-1875));
      aVLTree0.insert(0);
      aVLTree0.delete((-637));
      aVLTree0.find(1252);
      aVLTree0.delete(0);
      aVLTree0.delete((-1376));
      aVLTree0.insert((-637));
      aVLTree0.find(1252);
      aVLTree0.height();
      aVLTree0.insert((-418));
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      aVLTree0.find((-667));
      aVLTree0.insert((-675));
      aVLTree0.getBalance((AVLTree.Node) null);
      aVLTree0.find((-667));
      aVLTree0.delete(0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      aVLTree0.delete(426);
      aVLTree0.insert(426);
      aVLTree0.insert((-2420));
      aVLTree0.height();
      aVLTree0.insert((-3650));
      aVLTree0.height();
      aVLTree0.delete(426);
      aVLTree0.height();
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      int int0 = (-1120);
      aVLTree0.delete((-1120));
      aVLTree0.insert(953);
      aVLTree0.delete(0);
      aVLTree0.insert(0);
      aVLTree0.delete(951);
      aVLTree0.delete(0);
      aVLTree0.insert(0);
      aVLTree0.delete((-1666));
      int int1 = 1;
      // Undeclared exception!
      try { 
        aVLTree0.insert(0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // duplicate Key!
         //
         verifyException("AVLTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      aVLTree0.getRoot();
      aVLTree0.insert(0);
      aVLTree0.getBalance((AVLTree.Node) null);
      aVLTree0.insert((-1));
      aVLTree0.height();
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      int int0 = 834;
      aVLTree0.insert(834);
      aVLTree0.insert((-766));
      aVLTree0.insert((-1394));
      aVLTree0.insert((-662));
      aVLTree0.delete((-766));
      aVLTree0.height();
      int int1 = 0;
      aVLTree0.insert(0);
      aVLTree0.getRoot();
      aVLTree0.getRoot();
      aVLTree0.find(1);
      aVLTree0.find(1);
      aVLTree0.insert(1);
      aVLTree0.find((-766));
      aVLTree0.insert((-766));
      // Undeclared exception!
      try { 
        aVLTree0.insert(1);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // duplicate Key!
         //
         verifyException("AVLTree", e);
      }
  }

 /* @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      int int0 = 1;
      aVLTree0.delete(1);
      aVLTree0.insert(1);
      AVLTree.Node aVLTree_Node0 = aVLTree0.find(1);
      aVLTree_Node0.height = 1;
      aVLTree_Node0.height = (-668);
      aVLTree0.delete(111);
      aVLTree0.delete((-668));
      aVLTree_Node0.height = 1;
      aVLTree0.delete(1487);
      aVLTree0.height();
      int int1 = aVLTree0.getBalance(aVLTree_Node0);
      aVLTree_Node0.key = 1065;
      AVLTree.Node aVLTree_Node1 = aVLTree0.getRoot();
      aVLTree_Node0.right = aVLTree_Node1;
      aVLTree0.delete(0);
      aVLTree0.insert(int0);
      int int2 = 0;
      aVLTree0.insert(int2);
      AVLTree.Node aVLTree_Node2 = aVLTree0.getRoot();
      aVLTree0.find(int1);
      int int3 = 0;
      aVLTree_Node2.key = int3;
      aVLTree0.height();
      aVLTree0.getBalance(aVLTree_Node2);
      int int4 = 5;
      AVLTree.Node aVLTree_Node3 = aVLTree0.find(int4);
      aVLTree_Node3.right = aVLTree_Node2;
      aVLTree_Node3.key = int3;
      aVLTree0.getBalance(aVLTree_Node3);
      aVLTree0.height();
      aVLTree0.getRoot();
  }*/

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      aVLTree0.delete((-1));
      aVLTree0.insert((-1360));
      assertEquals(0, aVLTree0.height());
      
      aVLTree0.delete((-1360));
      aVLTree0.find((-1360));
      aVLTree0.delete((-1360));
      int int0 = aVLTree0.height();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      aVLTree0.delete(229);
      aVLTree0.delete(0);
      aVLTree0.insert(0);
      AVLTree.Node aVLTree_Node0 = aVLTree0.new Node(0);
      aVLTree0.insert(369);
      aVLTree_Node0.key = (-4462);
      aVLTree0.getBalance(aVLTree_Node0);
      aVLTree_Node0.height = 229;
      aVLTree0.height();
      aVLTree0.getBalance(aVLTree_Node0);
      aVLTree0.getBalance(aVLTree_Node0);
      aVLTree0.delete(129);
      aVLTree0.height();
      aVLTree0.insert(1);
      aVLTree0.find((-579));
      AVLTree.Node aVLTree_Node1 = aVLTree0.getRoot();
      aVLTree_Node1.height = 0;
      aVLTree0.getRoot();
      aVLTree0.getRoot();
      aVLTree_Node0.left = aVLTree_Node1;
      aVLTree0.insert((-1039));
      aVLTree0.find(0);
      aVLTree0.height();
      aVLTree0.getRoot();
      aVLTree0.find((-1351));
      // Undeclared exception!
      try { 
        aVLTree0.insert(0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // duplicate Key!
         //
         verifyException("AVLTree", e);
      }
  }
}
